# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\xaa\x01\n\nDataParams\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\'\n\x06params\x18\x02 \x03(\x0b\x32\x17.DataParams.ParamsEntry\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x02\x12\x0e\n\x06target\x18\x05 \x03(\x02\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8e\x01\n\x0bModelParams\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12(\n\x06params\x18\x02 \x03(\x0b\x32\x18.ModelParams.ParamsEntry\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"$\n\x0egetModelParams\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"1\n\rPredictParams\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"\x1d\n\x0b\x46itResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1f\n\rRefitResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\x0eRemoveResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"&\n\x0fPredictResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x02\"\x1c\n\x0cShowResponse\x12\x0c\n\x04show\x18\x01 \x01(\t2\xd0\x01\n\x05Model\x12 \n\x03\x66it\x12\x0b.DataParams\x1a\x0c.FitResponse\x12$\n\x05refit\x12\x0b.DataParams\x1a\x0e.RefitResponse\x12*\n\x06remove\x12\x0f.getModelParams\x1a\x0f.RemoveResponse\x12+\n\x07predict\x12\x0e.PredictParams\x1a\x10.PredictResponse\x12&\n\x04show\x12\x0f.getModelParams\x1a\r.ShowResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAPARAMS_PARAMSENTRY']._options = None
  _globals['_DATAPARAMS_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_MODELPARAMS_PARAMSENTRY']._options = None
  _globals['_MODELPARAMS_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_DATAPARAMS']._serialized_start=18
  _globals['_DATAPARAMS']._serialized_end=188
  _globals['_DATAPARAMS_PARAMSENTRY']._serialized_start=143
  _globals['_DATAPARAMS_PARAMSENTRY']._serialized_end=188
  _globals['_MODELPARAMS']._serialized_start=191
  _globals['_MODELPARAMS']._serialized_end=333
  _globals['_MODELPARAMS_PARAMSENTRY']._serialized_start=143
  _globals['_MODELPARAMS_PARAMSENTRY']._serialized_end=188
  _globals['_GETMODELPARAMS']._serialized_start=335
  _globals['_GETMODELPARAMS']._serialized_end=371
  _globals['_PREDICTPARAMS']._serialized_start=373
  _globals['_PREDICTPARAMS']._serialized_end=422
  _globals['_FITRESPONSE']._serialized_start=424
  _globals['_FITRESPONSE']._serialized_end=453
  _globals['_REFITRESPONSE']._serialized_start=455
  _globals['_REFITRESPONSE']._serialized_end=486
  _globals['_REMOVERESPONSE']._serialized_start=488
  _globals['_REMOVERESPONSE']._serialized_end=520
  _globals['_PREDICTRESPONSE']._serialized_start=522
  _globals['_PREDICTRESPONSE']._serialized_end=560
  _globals['_SHOWRESPONSE']._serialized_start=562
  _globals['_SHOWRESPONSE']._serialized_end=590
  _globals['_MODEL']._serialized_start=593
  _globals['_MODEL']._serialized_end=801
# @@protoc_insertion_point(module_scope)
